In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
os.chdir(r"C:\Users\EABPNHA\Desktop\DataScience Training\Exercise")

In [3]:
dataset = pd.read_csv('housing.csv')

In [4]:
dataset.columns
dataset.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200

In [5]:
# relevant_column = dataset.drop('median_income', axis =1)
# relevant_column.head(5)

In [6]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,9].values

In [7]:
from sklearn.preprocessing import Imputer
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_X = LabelEncoder()
X[:,8] = labelEncoder_X.fit_transform(X[:,8])
X

array([[-122.23, 37.88, 41, ..., 126, 8.3252, 3],
       [-122.22, 37.86, 21, ..., 1138, 8.3014, 3],
       [-122.24, 37.85, 52, ..., 177, 7.2574, 3],
       ...,
       [-121.22, 39.43, 17, ..., 433, 1.7, 1],
       [-121.32, 39.43, 18, ..., 349, 1.8672, 1],
       [-121.24, 39.37, 16, ..., 530, 2.3886, 1]], dtype=object)

In [9]:
imputer = Imputer(missing_values = 'NaN',strategy ='mean', axis =0)
imputer = imputer.fit(X[:,0:9])
X[:,0:9] = imputer.transform(X[:, 0:9])

In [10]:
onehotencoder = OneHotEncoder(categorical_features = [-2])
X = onehotencoder.fit_transform(X).toarray()
X

C:\Users\EABPNHA\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 3.220e+02, 1.260e+02,
        3.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.401e+03, 1.138e+03,
        3.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 4.960e+02, 1.770e+02,
        3.000e+00],
       ...,
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 1.007e+03, 4.330e+02,
        1.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 7.410e+02, 3.490e+02,
        1.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 1.387e+03, 5.300e+02,
        1.000e+00]])

In [11]:
labelEncoder_y = LabelEncoder()
y = labelEncoder_y.fit_transform(y)
y

array([3665, 3074, 3017, ...,  508,  432,  479], dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size =0.2, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
y_pred = regressor.predict(X_test)
y_pred

array([1703.23514325, 2166.86014325, 1435.73514325, ...,  502.86014325,
       2552.17264325, 1637.92264325])

In [58]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
rf = RandomForestClassifier(n_estimators = 100,random_state = 42 )
rf.fit(X_train,y_train)

MemoryError: could not allocate 239927296 bytes

In [54]:
rf.score(X_train,y_train)

NotFittedError: Estimator not fitted, call `fit` before exploiting the model.